[output]
name=HDMI-A-1
# normal, 90, 180, 270, flipped, flipped-90, flipped-180, flipped-270
transform=rotate-90

[shell]
panel-position=none
locking=false
cursor-theme=none

[core]
require-input=false
idle-time=0